Python Assignment 3
======

In [2]:
#Question 1
# 1. create a mini calculator that takes two inputs from the users and operator. 
# it should return the evaluation of the values entered.
# Eg. If the user enters 2, 4, *, it should return the value of 2 * 4.
# The same should apply if the user enters 10, 2, /. It should return 10/2

number1 = int(input("Enter first number: "))
number2 = int(input("Enter second number: "))
operator = input("Enter calculator operator: ")
if operator == '+' :
    print(f'For {number1} {operator} {number2}, the answer = ',number1 + number2)
elif operator == '*' :
    print(f'For {number1} {operator} {number2}, the answer = ',number1 * number2)
elif operator == '-' :
    print(f'For {number1} {operator} {number2}, the answer = ',number1 - number2)
elif operator == '/' :
    print(f'For {number1} {operator} {number2}, the answer = ', number1 / number2) 

Enter first number: 9
Enter second number: 12
Enter calculator operator: +
For 9 + 12, the answer =  21


In [3]:
# Question 2
# record = "this is the time to attend python training"
# bring out the words that start from 't'

record = "this is the time to attend python training"

record_list = record.split()
record_list
record = record_list[0],record_list[2],record_list[3],record_list[4],record_list[7]
record
" ".join(record)

'this the time to training'

In [4]:
# 3. create a program that generates a random number and ask the user to guess the number.
# If user guess right, print you win otherwise print, 
# guess is too large if the input is higher or guess is too low if input is lesser

import numpy as np
number = np.random.randint(10)
user_guess = int(input("Enter a number between 0 and 10: "))
print(f'Generated random number is {number}')

if number > user_guess:
    print("Your guess is too low")
elif number < user_guess:
    print("Your guess is too high")
elif number == user_guess:
    print("You win")

Enter a number between 0 and 10: 6
Generated random number is 4
Your guess is too high


In [5]:
# 4. Write a program that prints the integers from 1 to 100. 
# But for multiples of three print "Fizz" instead of the number, 
# and the multiples of five print "Buzz". 
# For numbers which are multiples of both three and five print "FizzBuzz".

In [6]:
for i in range(1,100):
    if i % 3 == 0 and i % 5 == 0:
        print('FizzBuzz')
    elif i % 3 == 0:
        print('Fizz')
    elif i % 5 == 0:
        print('Buzz')
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz


Numpy Assignment
======

In [7]:
# Question 1. Create an array of the integers from 10 to 50

import numpy as np
np_array = np.arange(10,51)
np_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
# Question 2. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
np_flat_array = np.arange(0,9)
np_3_x_3_array = np_flat_array.reshape(3,3)
np_3_x_3_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# Question 3. Use NumPy to generate an array of 25 random numbers sampled 
# from a standard normal distribution<br><br>
# NOTE: Your result's values should be different from the ones shown below.
import numpy as np
np_random = np.random.rand(25)
np_random = np_random.reshape(5,5)
np_random 

array([[2.67370768e-01, 5.84803073e-02, 8.19648142e-01, 1.18373383e-01,
        6.57996564e-01],
       [6.33285547e-01, 9.49902538e-01, 2.80346760e-01, 4.84152906e-01,
        4.94095283e-01],
       [5.43584545e-01, 3.08537816e-01, 9.98433756e-01, 3.74659504e-01,
        7.75234912e-01],
       [9.29520053e-01, 1.48524425e-04, 3.60554369e-02, 9.56095021e-01,
        5.39793092e-01],
       [9.90051030e-01, 2.30885922e-01, 2.42745415e-01, 6.51222736e-01,
        5.65262980e-01]])

In [10]:
# Question 4. create this matrix
# array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
#        [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
#        [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
#        [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
#        [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
#        [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
#        [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
#        [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
#        [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
#        [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

import numpy as np
np_random1 = np.random.rand(50)
np_random1 = np_random1.reshape(10,5)
np_random1

array([[0.45796646, 0.32758944, 0.70588022, 0.65588339, 0.09717654],
       [0.86411958, 0.09113262, 0.76548104, 0.451238  , 0.7023703 ],
       [0.28859485, 0.81266043, 0.27047784, 0.85973267, 0.61853755],
       [0.66571186, 0.79304544, 0.98087986, 0.52077626, 0.56101207],
       [0.72545023, 0.2540717 , 0.89250999, 0.08020931, 0.71602347],
       [0.99683188, 0.6724084 , 0.65527395, 0.64664964, 0.25944393],
       [0.01144947, 0.44234825, 0.39781024, 0.07417699, 0.08389801],
       [0.20121124, 0.26002073, 0.86480755, 0.38964698, 0.51112781],
       [0.17616551, 0.85506548, 0.29169526, 0.59771969, 0.30361795],
       [0.37987274, 0.83849271, 0.71354056, 0.47994404, 0.18044366]])

In [11]:
# Question 5. Create an array of 20 linearly spaced points between 0 and 1:
# Like the one below
# array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
#        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
#        0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
#        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

import numpy as np
np_line_spaced = np.linspace(0,1,20)
np_line_spaced

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# NB: use this data to solve subsequent challenges
import numpy as np
data = np.arange(1,26).reshape(5,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
# Question 7. bring out the follow from data above
# array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])

data[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# Question 8. produce the output below from the data above
# array([[ 2],
#        [ 7],
#        [12]])

data[1:4,1:2]

array([[ 7],
       [12],
       [17]])

In [15]:
# Question 9. produce the output below from the data above
# array([21, 22, 23, 24, 25])

data[4:5]

array([[21, 22, 23, 24, 25]])

In [16]:
# Question 10. Get the sum of all the values in data
data.sum()

325

In [17]:
# Question 11. Get the sum of all the columns in matrix
data.sum(axis=1)

array([ 15,  40,  65,  90, 115])